# 全局配置文件

# 服务器配置信息
Server:
  RunMode: release #开发模式debug 生产模式release
  HttpPort: 9091  #端口
  ReadTimeout: 60 #超时时间
  WriteTimeout: 60 #超时时间

# app配置信息
App:
  AppName: sheetServerApi #APP名称
  LogFilePath: /opt/report/log #日志记录位置
  LogFileName: system.log #日志名
  ReleaseUrl: http://localhost:9091/api/v2/sheets/ #生产环境的配置
  ConfigDir: /opt/report/configs #配置文件的测试目录
  ExcelFileDir: /opt/report/sheets/ #excel文件保存地址

# 数据库连接池 orm
DatabaseOrm:
  DBType: postgres
  Username: postgres
  Password:
  Host: localhost
  Port: 5432
  DBName: spreadsheet
  MaxIdleConns: 1
  MaxOpenConns: 2

# 数据库池 sqlx
DatabaseSqlx:
  DBType: postgres
  Username: postgres
  Password:
  Host: localhost
  Port: 5432
  DBName: spreadsheet
  MaxIdleConns: 1
  MaxOpenConns: 2